server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  client_max_body_size 20M;

  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;

  location = /runtime-config.js {
    add_header Cache-Control "no-store";
  }

  location = /build-id.txt {
    add_header Cache-Control "no-store";
    add_header Content-Type "text/plain";
  }

  location = /index.html {
    add_header Cache-Control "no-store";
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-store";
  }
}
